//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPP.APP.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProfile
    {
        public string UserTopLevel { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string DisplayName { get; set; }
        public string SecurityOrganization { get; set; }
        public string SecurityLocation { get; set; }
        public string SecurityDepartment { get; set; }
        public string Note { get; set; }
        public Nullable<long> Paging { get; set; }
        public string Options { get; set; }
        public string ProgramIDs { get; set; }
        public Nullable<int> Prefix { get; set; }
        public string UserRole { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public Nullable<int> ResourcePageID { get; set; }
    }
}
